# Generated by Django 3.0.5 on 2020-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('mobile', models.TextField()),
                ('dateofcontact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(default=1)),
                ('ipaddress', models.TextField()),
                ('status', models.TextField()),
                ('remarks', models.TextField(default='')),
                ('Sans', models.TextField(default='')),
                ('Pysbil', models.TextField(default='')),
                ('VirusTotal', models.TextField(default='')),
                ('IbmXForce', models.TextField(default='')),
            ],
        ),
    ]
