# Generated by Django 3.0.2 on 2020-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='reference',
            field=models.TextField(default=1),
        ),
    ]
