# Generated by Django 3.0.6 on 2020-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('hashes', models.TextField()),
                ('family', models.TextField()),
                ('type', models.TextField()),
                ('risk', models.TextField()),
            ],
        ),
    ]
