# Generated by Django 3.0.2 on 2020-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_ips_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
