# Generated by Django 3.0.6 on 2020-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdata',
            name='hashcount',
            field=models.IntegerField(default=1),
        ),
    ]
