# Generated by Django 3.0.2 on 2020-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_ips_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('mobile', models.TextField()),
                ('dateofcontact', models.TextField()),
            ],
        ),
    ]
