# Generated by Django 3.0.6 on 2020-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_ipdata_hashcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashes',
            name='family',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='hashes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='reference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='risk',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
