# Generated by Django 3.0.5 on 2020-05-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ips',
            name='IbmXForce',
        ),
        migrations.RemoveField(
            model_name='ips',
            name='Pysbil',
        ),
        migrations.RemoveField(
            model_name='ips',
            name='Sans',
        ),
        migrations.RemoveField(
            model_name='ips',
            name='VirusTotal',
        ),
    ]
