# Generated by Django 3.0.5 on 2020-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200501_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('blklistcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipcount', models.IntegerField()),
                ('blacklistedip', models.IntegerField()),
                ('goodip', models.IntegerField()),
                ('domaincount', models.IntegerField()),
            ],
        ),
    ]
